// <auto-generated />
using System;
using Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Web.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220408191559_Slug")]
    partial class Slug
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entidades.Eventos.EVENTOS", b =>
                {
                    b.Property<long>("ID_EVENTO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DESCRIPCION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESTADO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FECHA_CREACION")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FECHA_FIN")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FECHA_INICIO")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FECHA_MODIFICACION")
                        .HasColumnType("datetime2");

                    b.Property<long>("ID_NEGOCIO")
                        .HasColumnType("bigint");

                    b.Property<int>("MAXIMO_VENTAS")
                        .HasColumnType("int");

                    b.Property<string>("NOMBRE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL_IMG_CABECERA")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_EVENTO");

                    b.HasIndex("ID_NEGOCIO");

                    b.ToTable("EVENTOS");
                });

            modelBuilder.Entity("Entidades.Negocios.NEGOCIOS", b =>
                {
                    b.Property<long>("ID_NEGOCIO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DESCRIPCION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ID_TIPO_NEGOCIO")
                        .HasColumnType("bigint");

                    b.Property<string>("NOMBRE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SLUG")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SLUG")
                        .HasAnnotation("Unique", true);

                    b.Property<string>("UBICACION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL_IMG_CABECERA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL_LOGO")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_NEGOCIO");

                    b.HasIndex("ID_TIPO_NEGOCIO");

                    b.ToTable("NEGOCIOS");
                });

            modelBuilder.Entity("Entidades.Negocios.NEGOCIO_USUARIO", b =>
                {
                    b.Property<long>("ID_NEGOCIO_USUARIO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ID_NEGOCIO")
                        .HasColumnType("bigint");

                    b.Property<long>("ID_USUARIO")
                        .HasColumnType("bigint");

                    b.HasKey("ID_NEGOCIO_USUARIO");

                    b.HasIndex("ID_NEGOCIO");

                    b.HasIndex("ID_USUARIO");

                    b.ToTable("NEGOCIO_USUARIO");
                });

            modelBuilder.Entity("Entidades.Servicios.SERVICIOS", b =>
                {
                    b.Property<long>("ID_SERVICIO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CANTIDAD")
                        .HasColumnType("int");

                    b.Property<int>("CANTIDAD_MAX_PP")
                        .HasColumnType("int");

                    b.Property<string>("DESCRIPCION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FECHA_FIN_VENTA")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FECHA_INICIO_VENTA")
                        .HasColumnType("datetime2");

                    b.Property<long>("ID_ESTADO_SERVICIO")
                        .HasColumnType("bigint");

                    b.Property<long>("ID_EVENTO")
                        .HasColumnType("bigint");

                    b.Property<string>("NOMBRE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PRECIO")
                        .HasColumnType("float");

                    b.Property<double>("PRECIO_EN_PUERTA")
                        .HasColumnType("float");

                    b.Property<bool>("VISIBILIDAD")
                        .HasColumnType("bit");

                    b.HasKey("ID_SERVICIO");

                    b.HasIndex("ID_EVENTO");

                    b.ToTable("SERVICIOS");
                });

            modelBuilder.Entity("Entidades.TipoNegocio.TIPO_NEGOCIO", b =>
                {
                    b.Property<long>("ID_TIPO_NEGOCIO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NOMBRE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_TIPO_NEGOCIO");

                    b.ToTable("TIPO_NEGOCIO");
                });

            modelBuilder.Entity("Entidades.Usuarios.USUARIOS", b =>
                {
                    b.Property<long>("ID_USUARIO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("APELLIDOS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FECHA_NACIMIENTO")
                        .HasColumnType("datetime2");

                    b.Property<string>("NOMBRE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PASSWORD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TELEFONO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USUARIO")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_USUARIO");

                    b.ToTable("USUARIOS");
                });

            modelBuilder.Entity("Entidades.Eventos.EVENTOS", b =>
                {
                    b.HasOne("Entidades.Negocios.NEGOCIOS", "NEGOCIO")
                        .WithMany()
                        .HasForeignKey("ID_NEGOCIO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NEGOCIO");
                });

            modelBuilder.Entity("Entidades.Negocios.NEGOCIOS", b =>
                {
                    b.HasOne("Entidades.TipoNegocio.TIPO_NEGOCIO", "TIPO_NEGOCIO")
                        .WithMany()
                        .HasForeignKey("ID_TIPO_NEGOCIO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TIPO_NEGOCIO");
                });

            modelBuilder.Entity("Entidades.Negocios.NEGOCIO_USUARIO", b =>
                {
                    b.HasOne("Entidades.Negocios.NEGOCIOS", "NEGOCIOS")
                        .WithMany()
                        .HasForeignKey("ID_NEGOCIO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entidades.Usuarios.USUARIOS", "USUARIOS")
                        .WithMany()
                        .HasForeignKey("ID_USUARIO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NEGOCIOS");

                    b.Navigation("USUARIOS");
                });

            modelBuilder.Entity("Entidades.Servicios.SERVICIOS", b =>
                {
                    b.HasOne("Entidades.Eventos.EVENTOS", "EVENTOS")
                        .WithMany()
                        .HasForeignKey("ID_EVENTO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EVENTOS");
                });
#pragma warning restore 612, 618
        }
    }
}
